resources:
- name: 15m
  type: time
  source: {interval: 15m}

- name: ccc-git
  type: git
  source:
    branch: master
    uri: git@github.com:staynerzone/candy-cloudy-care.git
    private_key: ((git.private_key))

resource_types:

jobs:

- name: check-openstack-api-response-time
  plan:
  - get: ccc-git
  - get: 15m
  - task: check-repsonse-times
    file: ccc-git/tasks/openstack-cli/task.yml
    params:
     <<: &oscreds
        OS_AUTH_URL: ((os_auth_url))
        OS_USERNAME: ((os_username))
        OS_PASSWORD: ((os_password))
        OS_PROJECT_NAME: ((os_project_name))
