resources:
- name: 15m
  type: time
  source: {interval: 15m}

- name: keyval
  type: keyval

- name: ccc-git
  type: git
  source:
    branch: master
    uri: git@github.com:staynerzone/candy-cloudy-care.git
    private_key: ((git.private_key))

resource_types:
- name: keyval
  type: docker-image
  source:
    repository: swce/keyval-resource

jobs:
- name: check-keystone-authentification
  plan:
  - get: ccc-git
  - get: 15m
    trigger: true
  - task: check-keystone-authentification
    file: ccc-git/tasks/check-keystone-auth/task.yml
  - put: keyval
    params:
      file: token/token

- name: check-openstack-apis
  plan:
  - get: ccc-git
  - get: 15m
    trigger: true
    passed: [check-keystone-authentification]
  - get: keyval
  - task: check-openstack-apis
    file: ccc-git/tasks/check-openstack-apis/task.yml
    params:
      <<: &oscreds
        OS_AUTH_URL: ((os_auth_url))
        OS_USERNAME: ((os_username))
        OS_PASSWORD: ((os_password))
        OS_PROJECT_NAME: ((os_project_name))


    
